// src/types/api.ts
export const apiSliceTags: string[] = [
  'DashboardStats',
  'Users',
  'User',
  'Posts',
  'Post',
  'Categories',
  'Category',
  'CategoryStats',
  'Events',
  'Event',
  'EventCategory',
  'EventCategoryStats',
  'Guides',
  'Guide',
  'Projects',
  'Project',
  'GalleryPhotos',
  'GalleryPhoto',
  'GalleryCategories',
  'GalleryCategory',
  'TeamMembers',
  'TeamMember',
];
